services:
  flask:
    build: .
    volumes:
      - app:/app
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"